+copy invite link to clipboard from invite action menu
docmost/docmost pull request #360
Opened 2024-10-02 18:07 UTC by NomadRazor

This PR added copy to invite link action to invite action menu for all who deploy Docmost without email account settings and wants  invite friends. 
The invitation link is copied to the clipboard.
![cpl](https://github.com/user-attachments/assets/05b453f4-b266-4ff9-aa2b-3277a776eafe)

2024-10-02 18:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/docmost/docmost?pullRequest=360) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/docmost/docmost?pullRequest=360) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/docmost/docmost?pullRequest=360) it.</sub>

2024-10-05 04:31 UTC, aayushchugh requested changes

2024-10-05 04:31 UTC, aayushchugh commented on apps/client/src/features/workspace/components/members/components/invite-action-menu.tsx
> +      console.log(error)
👀

2024-10-07 23:23 UTC, NomadRazor commented on apps/client/src/features/workspace/components/members/components/invite-action-menu.tsx
> +      console.log(error)
Sorry, I just forgot.

2024-10-21 08:51 UTC, thevops commented
Does it know when it will be done?

2024-10-21 10:31 UTC, aayushchugh commented
We are not sure when will they review this PR.

2024-10-21 11:05 UTC, Philipinho commented
I am not sure I would like to expose the invite link in this manner. I plan to introduce a workspace-level invite link you can share with anyone.

2025-02-26 17:23 UTC, Philipinho commented
It seems interesting to revisit this.

2025-02-26 18:28 UTC, merged

2025-02-26 18:29 UTC, Philipinho commented
Thank you for your contribution.