feat: deactivate user
docmost/docmost pull request #373
Opened 2024-10-05 05:33 UTC by aayushchugh

This is 1/2 PRs for #177 

In this PR, the owner and admin can deactivate a member.

I would greatly appreciate any feedback.

## Frontend tasks

- [ ] Create a button to deactivate the user
- [ ] List all deactivated users
- [ ] Validations
    - [ ] Admin can't delete owner
    - [ ] Member can't delete admin
    - [ ] Users can't delete themselves

## Backend tasks

- [ ] Route to deactivate user
- [ ] Validations
    - [ ] Admin can't delete owner
    - [ ] Member can't delete admin
    - [ ] Users can't delete themselves
 - [ ] New route to list all deactivated users

2024-10-05 05:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/docmost/docmost?pullRequest=373) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/docmost/docmost?pullRequest=373) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/docmost/docmost?pullRequest=373) it.</sub>

2024-10-21 17:19 UTC, aayushchugh commented
Any update on this?

2024-10-26 16:22 UTC, Philipinho requested changes

2024-10-26 16:22 UTC, Philipinho commented on apps/server/src/core/workspace/services/workspace.service.ts
> +      'OWNER',
All usages of `OWNER` and `ADMIN` should be `UserRole.OWNER` imported from `/common/helpers/types/permission`.

2024-10-26 16:22 UTC, Philipinho commented on apps/server/src/database/types/db.d.ts
> +  emailDomains: Generated<string[] | null>;
I am not sure why the change here. The database column is named `allowed_email_domains`.

This file generated from the database schema by running ```pnpm nx run server:migration:codegen```.

2024-10-26 16:22 UTC, Philipinho commented on apps/client/src/pages/settings/workspace/workspace-members.tsx
> +						{ label: "Deactivated", value: "deactivated" },
I am not in favor of having another SegmentedControl tab.
I am thinking we could have a filter button which when ticked would show the deactivated users on the already existing "Members" tab.

2024-10-26 16:22 UTC, Philipinho commented on apps/client/src/features/workspace/components/members/components/workspace-members-table.tsx
> +								<Tooltip label="Deactivate member">
The UI should be consistent with what we have in the Space Members section. 
It should be a menu with dots as the trigger icon. By doing this, we can easily add more actions in the future.
<img width="569" alt="image" src="https://github.com/user-attachments/assets/e5e01f8a-ba5f-42b0-b5d9-34c55094a4a4">

2025-01-05 06:48 UTC, SimonHoiberg commented
Any update on this? Or any way I can help? 😊
This feature would be highly convenient!

2025-01-05 06:52 UTC, aayushchugh commented
@SimonHoiberg I'll do required changes by next week

2025-02-16 12:23 UTC, aayushchugh commented
Closing this because of multiple conflicts, I'll create a new PR

2025-02-16 12:23 UTC, closed without merging